logging:
    level:
        org.springframework.cloud.stream.messaging.DirectWithAttributesChannel: DEBUG
it:
  dsibilio:
    binder:
      root: /Temp/binder/data
spring:
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  cloud:
    function:
      definition: getSampleDetails;streamErrorHandler
    stream:
      defaultBinder: rabbit
      bindings:
        getSampleDetails-in-0:
          destination: sample-details-req
          group: stream-sample-details-req
        getSampleDetails-out-0:
          destination: sample-details-resp
          content-type: application/json
          producer:
            required-groups: gateway-sample-details-resp 