#trace: true
#debug: true
logging:
    level:
#        org.springframework.cloud.stream.messaging.DirectWithAttributesChannel: DEBUG
        org.springframework.cloud.stream: DEBUG
        org.springframework.integration: DEBUG
        org.springframework.amqp: DEBUG
        
springdoc:
  api-docs:
    enabled: true
  packagesToScan: org.streamy.rest
  pathsToMatch: /v1, /sample/**
  cache:
    disabled: true
  writer-with-default-pretty-printer: true
  swagger-ui:
    # True is default
    enabled: true
    path: /swagger-ui
    url: /v3/api-docs
    config-url: /v3/api-docs/swagger-config
    use-root-path: true
    doc-expansion: none
    disable-swagger-default-url: true
    operationsSorter: method
    # show lengths patterns and the like.
    showCommonExtensions: true
    # Name of swagger group to load upon entry.  Doesn't seem to affect us because we don't use groups. Not yet needed.
    urlsPrimaryName: swaggerGroup 
  

spring:
  rabbit:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  cloud:
    function:         
      definition: getSampleDetails
      defaultBinder: rabbit
      rabbit:
        bindings:
          getSampleDetails-in-0:
            consumer:
              auto-bind-dlq: true
              republishToDlq: true        
              dlq-ttl: 50000
##              republishToDlq: true        
    stream:  
      bindings:
#        sample-details-req: 
        getSampleDetails-out-0: 
          destination: sample-details-req
#          producer:
#            required-groups: stream-sample-details-req
        getSampleDetails-in-0:
          destination: sample-details-resp
          content-type: application/json
          group: get_sampl_dets
#       getSampleDetailsErrors-in-0:
#         destination: sample-details-req.get_sampl_dets.dlq
#          
